// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cowcow.proto

#ifndef PROTOBUF_INCLUDED_cowcow_2eproto
#define PROTOBUF_INCLUDED_cowcow_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_cowcow_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_cowcow_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_cowcow_2eproto();
namespace go {
class GameCowcowBetResult;
class GameCowcowBetResultDefaultTypeInternal;
extern GameCowcowBetResultDefaultTypeInternal _GameCowcowBetResult_default_instance_;
class GameCowcowEnter;
class GameCowcowEnterDefaultTypeInternal;
extern GameCowcowEnterDefaultTypeInternal _GameCowcowEnter_default_instance_;
class GameCowcowOver;
class GameCowcowOverDefaultTypeInternal;
extern GameCowcowOverDefaultTypeInternal _GameCowcowOver_default_instance_;
class GameCowcowPlaying;
class GameCowcowPlayingDefaultTypeInternal;
extern GameCowcowPlayingDefaultTypeInternal _GameCowcowPlaying_default_instance_;
}  // namespace go
namespace google {
namespace protobuf {
template<> ::go::GameCowcowBetResult* Arena::CreateMaybeMessage<::go::GameCowcowBetResult>(Arena*);
template<> ::go::GameCowcowEnter* Arena::CreateMaybeMessage<::go::GameCowcowEnter>(Arena*);
template<> ::go::GameCowcowOver* Arena::CreateMaybeMessage<::go::GameCowcowOver>(Arena*);
template<> ::go::GameCowcowPlaying* Arena::CreateMaybeMessage<::go::GameCowcowPlaying>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace go {

// ===================================================================

class GameCowcowEnter final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:go.GameCowcowEnter) */ {
 public:
  GameCowcowEnter();
  virtual ~GameCowcowEnter();

  GameCowcowEnter(const GameCowcowEnter& from);

  inline GameCowcowEnter& operator=(const GameCowcowEnter& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GameCowcowEnter(GameCowcowEnter&& from) noexcept
    : GameCowcowEnter() {
    *this = ::std::move(from);
  }

  inline GameCowcowEnter& operator=(GameCowcowEnter&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GameCowcowEnter& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GameCowcowEnter* internal_default_instance() {
    return reinterpret_cast<const GameCowcowEnter*>(
               &_GameCowcowEnter_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(GameCowcowEnter* other);
  friend void swap(GameCowcowEnter& a, GameCowcowEnter& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GameCowcowEnter* New() const final {
    return CreateMaybeMessage<GameCowcowEnter>(nullptr);
  }

  GameCowcowEnter* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GameCowcowEnter>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GameCowcowEnter& from);
  void MergeFrom(const GameCowcowEnter& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameCowcowEnter* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 AwardAreas = 1;
  int awardareas_size() const;
  void clear_awardareas();
  static const int kAwardAreasFieldNumber = 1;
  ::google::protobuf::int32 awardareas(int index) const;
  void set_awardareas(int index, ::google::protobuf::int32 value);
  void add_awardareas(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      awardareas() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_awardareas();

  // repeated string players = 2;
  int players_size() const;
  void clear_players();
  static const int kPlayersFieldNumber = 2;
  const ::std::string& players(int index) const;
  ::std::string* mutable_players(int index);
  void set_players(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_players(int index, ::std::string&& value);
  #endif
  void set_players(int index, const char* value);
  void set_players(int index, const char* value, size_t size);
  ::std::string* add_players();
  void add_players(const ::std::string& value);
  #if LANG_CXX11
  void add_players(::std::string&& value);
  #endif
  void add_players(const char* value);
  void add_players(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField<::std::string>& players() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* mutable_players();

  // repeated int32 Chips = 4;
  int chips_size() const;
  void clear_chips();
  static const int kChipsFieldNumber = 4;
  ::google::protobuf::int32 chips(int index) const;
  void set_chips(int index, ::google::protobuf::int32 value);
  void add_chips(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      chips() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_chips();

  // repeated int32 Odds = 5;
  int odds_size() const;
  void clear_odds();
  static const int kOddsFieldNumber = 5;
  ::google::protobuf::int32 odds(int index) const;
  void set_odds(int index, ::google::protobuf::int32 value);
  void add_odds(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      odds() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_odds();

  // int64 BankerScore = 6;
  void clear_bankerscore();
  static const int kBankerScoreFieldNumber = 6;
  ::google::protobuf::int64 bankerscore() const;
  void set_bankerscore(::google::protobuf::int64 value);

  // int64 PlayerScore = 7;
  void clear_playerscore();
  static const int kPlayerScoreFieldNumber = 7;
  ::google::protobuf::int64 playerscore() const;
  void set_playerscore(::google::protobuf::int64 value);

  // int64 Acquire = 8;
  void clear_acquire();
  static const int kAcquireFieldNumber = 8;
  ::google::protobuf::int64 acquire() const;
  void set_acquire(::google::protobuf::int64 value);

  // int32 Countdown = 3;
  void clear_countdown();
  static const int kCountdownFieldNumber = 3;
  ::google::protobuf::int32 countdown() const;
  void set_countdown(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:go.GameCowcowEnter)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > awardareas_;
  mutable std::atomic<int> _awardareas_cached_byte_size_;
  ::google::protobuf::RepeatedPtrField<::std::string> players_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > chips_;
  mutable std::atomic<int> _chips_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > odds_;
  mutable std::atomic<int> _odds_cached_byte_size_;
  ::google::protobuf::int64 bankerscore_;
  ::google::protobuf::int64 playerscore_;
  ::google::protobuf::int64 acquire_;
  ::google::protobuf::int32 countdown_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cowcow_2eproto;
};
// -------------------------------------------------------------------

class GameCowcowPlaying final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:go.GameCowcowPlaying) */ {
 public:
  GameCowcowPlaying();
  virtual ~GameCowcowPlaying();

  GameCowcowPlaying(const GameCowcowPlaying& from);

  inline GameCowcowPlaying& operator=(const GameCowcowPlaying& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GameCowcowPlaying(GameCowcowPlaying&& from) noexcept
    : GameCowcowPlaying() {
    *this = ::std::move(from);
  }

  inline GameCowcowPlaying& operator=(GameCowcowPlaying&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GameCowcowPlaying& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GameCowcowPlaying* internal_default_instance() {
    return reinterpret_cast<const GameCowcowPlaying*>(
               &_GameCowcowPlaying_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(GameCowcowPlaying* other);
  friend void swap(GameCowcowPlaying& a, GameCowcowPlaying& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GameCowcowPlaying* New() const final {
    return CreateMaybeMessage<GameCowcowPlaying>(nullptr);
  }

  GameCowcowPlaying* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GameCowcowPlaying>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GameCowcowPlaying& from);
  void MergeFrom(const GameCowcowPlaying& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameCowcowPlaying* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int64 BetScore = 2;
  void clear_betscore();
  static const int kBetScoreFieldNumber = 2;
  ::google::protobuf::int64 betscore() const;
  void set_betscore(::google::protobuf::int64 value);

  // int32 BetArea = 1;
  void clear_betarea();
  static const int kBetAreaFieldNumber = 1;
  ::google::protobuf::int32 betarea() const;
  void set_betarea(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:go.GameCowcowPlaying)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int64 betscore_;
  ::google::protobuf::int32 betarea_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cowcow_2eproto;
};
// -------------------------------------------------------------------

class GameCowcowBetResult final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:go.GameCowcowBetResult) */ {
 public:
  GameCowcowBetResult();
  virtual ~GameCowcowBetResult();

  GameCowcowBetResult(const GameCowcowBetResult& from);

  inline GameCowcowBetResult& operator=(const GameCowcowBetResult& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GameCowcowBetResult(GameCowcowBetResult&& from) noexcept
    : GameCowcowBetResult() {
    *this = ::std::move(from);
  }

  inline GameCowcowBetResult& operator=(GameCowcowBetResult&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GameCowcowBetResult& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GameCowcowBetResult* internal_default_instance() {
    return reinterpret_cast<const GameCowcowBetResult*>(
               &_GameCowcowBetResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(GameCowcowBetResult* other);
  friend void swap(GameCowcowBetResult& a, GameCowcowBetResult& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GameCowcowBetResult* New() const final {
    return CreateMaybeMessage<GameCowcowBetResult>(nullptr);
  }

  GameCowcowBetResult* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GameCowcowBetResult>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GameCowcowBetResult& from);
  void MergeFrom(const GameCowcowBetResult& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameCowcowBetResult* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string Hints = 2;
  void clear_hints();
  static const int kHintsFieldNumber = 2;
  const ::std::string& hints() const;
  void set_hints(const ::std::string& value);
  #if LANG_CXX11
  void set_hints(::std::string&& value);
  #endif
  void set_hints(const char* value);
  void set_hints(const char* value, size_t size);
  ::std::string* mutable_hints();
  ::std::string* release_hints();
  void set_allocated_hints(::std::string* hints);

  // int32 State = 1;
  void clear_state();
  static const int kStateFieldNumber = 1;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:go.GameCowcowBetResult)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr hints_;
  ::google::protobuf::int32 state_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cowcow_2eproto;
};
// -------------------------------------------------------------------

class GameCowcowOver final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:go.GameCowcowOver) */ {
 public:
  GameCowcowOver();
  virtual ~GameCowcowOver();

  GameCowcowOver(const GameCowcowOver& from);

  inline GameCowcowOver& operator=(const GameCowcowOver& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GameCowcowOver(GameCowcowOver&& from) noexcept
    : GameCowcowOver() {
    *this = ::std::move(from);
  }

  inline GameCowcowOver& operator=(GameCowcowOver&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const GameCowcowOver& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GameCowcowOver* internal_default_instance() {
    return reinterpret_cast<const GameCowcowOver*>(
               &_GameCowcowOver_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(GameCowcowOver* other);
  friend void swap(GameCowcowOver& a, GameCowcowOver& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GameCowcowOver* New() const final {
    return CreateMaybeMessage<GameCowcowOver>(nullptr);
  }

  GameCowcowOver* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<GameCowcowOver>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const GameCowcowOver& from);
  void MergeFrom(const GameCowcowOver& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(GameCowcowOver* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 AwardArea = 1;
  int awardarea_size() const;
  void clear_awardarea();
  static const int kAwardAreaFieldNumber = 1;
  ::google::protobuf::int32 awardarea(int index) const;
  void set_awardarea(int index, ::google::protobuf::int32 value);
  void add_awardarea(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      awardarea() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_awardarea();

  // repeated int32 PlayerCard = 2;
  int playercard_size() const;
  void clear_playercard();
  static const int kPlayerCardFieldNumber = 2;
  ::google::protobuf::int32 playercard(int index) const;
  void set_playercard(int index, ::google::protobuf::int32 value);
  void add_playercard(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      playercard() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_playercard();

  // repeated int32 BankerCard = 3;
  int bankercard_size() const;
  void clear_bankercard();
  static const int kBankerCardFieldNumber = 3;
  ::google::protobuf::int32 bankercard(int index) const;
  void set_bankercard(int index, ::google::protobuf::int32 value);
  void add_bankercard(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      bankercard() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_bankercard();

  // int64 Acquire = 4;
  void clear_acquire();
  static const int kAcquireFieldNumber = 4;
  ::google::protobuf::int64 acquire() const;
  void set_acquire(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:go.GameCowcowOver)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > awardarea_;
  mutable std::atomic<int> _awardarea_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > playercard_;
  mutable std::atomic<int> _playercard_cached_byte_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > bankercard_;
  mutable std::atomic<int> _bankercard_cached_byte_size_;
  ::google::protobuf::int64 acquire_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_cowcow_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// GameCowcowEnter

// repeated int32 AwardAreas = 1;
inline int GameCowcowEnter::awardareas_size() const {
  return awardareas_.size();
}
inline void GameCowcowEnter::clear_awardareas() {
  awardareas_.Clear();
}
inline ::google::protobuf::int32 GameCowcowEnter::awardareas(int index) const {
  // @@protoc_insertion_point(field_get:go.GameCowcowEnter.AwardAreas)
  return awardareas_.Get(index);
}
inline void GameCowcowEnter::set_awardareas(int index, ::google::protobuf::int32 value) {
  awardareas_.Set(index, value);
  // @@protoc_insertion_point(field_set:go.GameCowcowEnter.AwardAreas)
}
inline void GameCowcowEnter::add_awardareas(::google::protobuf::int32 value) {
  awardareas_.Add(value);
  // @@protoc_insertion_point(field_add:go.GameCowcowEnter.AwardAreas)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
GameCowcowEnter::awardareas() const {
  // @@protoc_insertion_point(field_list:go.GameCowcowEnter.AwardAreas)
  return awardareas_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
GameCowcowEnter::mutable_awardareas() {
  // @@protoc_insertion_point(field_mutable_list:go.GameCowcowEnter.AwardAreas)
  return &awardareas_;
}

// repeated string players = 2;
inline int GameCowcowEnter::players_size() const {
  return players_.size();
}
inline void GameCowcowEnter::clear_players() {
  players_.Clear();
}
inline const ::std::string& GameCowcowEnter::players(int index) const {
  // @@protoc_insertion_point(field_get:go.GameCowcowEnter.players)
  return players_.Get(index);
}
inline ::std::string* GameCowcowEnter::mutable_players(int index) {
  // @@protoc_insertion_point(field_mutable:go.GameCowcowEnter.players)
  return players_.Mutable(index);
}
inline void GameCowcowEnter::set_players(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:go.GameCowcowEnter.players)
  players_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void GameCowcowEnter::set_players(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:go.GameCowcowEnter.players)
  players_.Mutable(index)->assign(std::move(value));
}
#endif
inline void GameCowcowEnter::set_players(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  players_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:go.GameCowcowEnter.players)
}
inline void GameCowcowEnter::set_players(int index, const char* value, size_t size) {
  players_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:go.GameCowcowEnter.players)
}
inline ::std::string* GameCowcowEnter::add_players() {
  // @@protoc_insertion_point(field_add_mutable:go.GameCowcowEnter.players)
  return players_.Add();
}
inline void GameCowcowEnter::add_players(const ::std::string& value) {
  players_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:go.GameCowcowEnter.players)
}
#if LANG_CXX11
inline void GameCowcowEnter::add_players(::std::string&& value) {
  players_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:go.GameCowcowEnter.players)
}
#endif
inline void GameCowcowEnter::add_players(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  players_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:go.GameCowcowEnter.players)
}
inline void GameCowcowEnter::add_players(const char* value, size_t size) {
  players_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:go.GameCowcowEnter.players)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
GameCowcowEnter::players() const {
  // @@protoc_insertion_point(field_list:go.GameCowcowEnter.players)
  return players_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>*
GameCowcowEnter::mutable_players() {
  // @@protoc_insertion_point(field_mutable_list:go.GameCowcowEnter.players)
  return &players_;
}

// int32 Countdown = 3;
inline void GameCowcowEnter::clear_countdown() {
  countdown_ = 0;
}
inline ::google::protobuf::int32 GameCowcowEnter::countdown() const {
  // @@protoc_insertion_point(field_get:go.GameCowcowEnter.Countdown)
  return countdown_;
}
inline void GameCowcowEnter::set_countdown(::google::protobuf::int32 value) {
  
  countdown_ = value;
  // @@protoc_insertion_point(field_set:go.GameCowcowEnter.Countdown)
}

// repeated int32 Chips = 4;
inline int GameCowcowEnter::chips_size() const {
  return chips_.size();
}
inline void GameCowcowEnter::clear_chips() {
  chips_.Clear();
}
inline ::google::protobuf::int32 GameCowcowEnter::chips(int index) const {
  // @@protoc_insertion_point(field_get:go.GameCowcowEnter.Chips)
  return chips_.Get(index);
}
inline void GameCowcowEnter::set_chips(int index, ::google::protobuf::int32 value) {
  chips_.Set(index, value);
  // @@protoc_insertion_point(field_set:go.GameCowcowEnter.Chips)
}
inline void GameCowcowEnter::add_chips(::google::protobuf::int32 value) {
  chips_.Add(value);
  // @@protoc_insertion_point(field_add:go.GameCowcowEnter.Chips)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
GameCowcowEnter::chips() const {
  // @@protoc_insertion_point(field_list:go.GameCowcowEnter.Chips)
  return chips_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
GameCowcowEnter::mutable_chips() {
  // @@protoc_insertion_point(field_mutable_list:go.GameCowcowEnter.Chips)
  return &chips_;
}

// repeated int32 Odds = 5;
inline int GameCowcowEnter::odds_size() const {
  return odds_.size();
}
inline void GameCowcowEnter::clear_odds() {
  odds_.Clear();
}
inline ::google::protobuf::int32 GameCowcowEnter::odds(int index) const {
  // @@protoc_insertion_point(field_get:go.GameCowcowEnter.Odds)
  return odds_.Get(index);
}
inline void GameCowcowEnter::set_odds(int index, ::google::protobuf::int32 value) {
  odds_.Set(index, value);
  // @@protoc_insertion_point(field_set:go.GameCowcowEnter.Odds)
}
inline void GameCowcowEnter::add_odds(::google::protobuf::int32 value) {
  odds_.Add(value);
  // @@protoc_insertion_point(field_add:go.GameCowcowEnter.Odds)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
GameCowcowEnter::odds() const {
  // @@protoc_insertion_point(field_list:go.GameCowcowEnter.Odds)
  return odds_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
GameCowcowEnter::mutable_odds() {
  // @@protoc_insertion_point(field_mutable_list:go.GameCowcowEnter.Odds)
  return &odds_;
}

// int64 BankerScore = 6;
inline void GameCowcowEnter::clear_bankerscore() {
  bankerscore_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 GameCowcowEnter::bankerscore() const {
  // @@protoc_insertion_point(field_get:go.GameCowcowEnter.BankerScore)
  return bankerscore_;
}
inline void GameCowcowEnter::set_bankerscore(::google::protobuf::int64 value) {
  
  bankerscore_ = value;
  // @@protoc_insertion_point(field_set:go.GameCowcowEnter.BankerScore)
}

// int64 PlayerScore = 7;
inline void GameCowcowEnter::clear_playerscore() {
  playerscore_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 GameCowcowEnter::playerscore() const {
  // @@protoc_insertion_point(field_get:go.GameCowcowEnter.PlayerScore)
  return playerscore_;
}
inline void GameCowcowEnter::set_playerscore(::google::protobuf::int64 value) {
  
  playerscore_ = value;
  // @@protoc_insertion_point(field_set:go.GameCowcowEnter.PlayerScore)
}

// int64 Acquire = 8;
inline void GameCowcowEnter::clear_acquire() {
  acquire_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 GameCowcowEnter::acquire() const {
  // @@protoc_insertion_point(field_get:go.GameCowcowEnter.Acquire)
  return acquire_;
}
inline void GameCowcowEnter::set_acquire(::google::protobuf::int64 value) {
  
  acquire_ = value;
  // @@protoc_insertion_point(field_set:go.GameCowcowEnter.Acquire)
}

// -------------------------------------------------------------------

// GameCowcowPlaying

// int32 BetArea = 1;
inline void GameCowcowPlaying::clear_betarea() {
  betarea_ = 0;
}
inline ::google::protobuf::int32 GameCowcowPlaying::betarea() const {
  // @@protoc_insertion_point(field_get:go.GameCowcowPlaying.BetArea)
  return betarea_;
}
inline void GameCowcowPlaying::set_betarea(::google::protobuf::int32 value) {
  
  betarea_ = value;
  // @@protoc_insertion_point(field_set:go.GameCowcowPlaying.BetArea)
}

// int64 BetScore = 2;
inline void GameCowcowPlaying::clear_betscore() {
  betscore_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 GameCowcowPlaying::betscore() const {
  // @@protoc_insertion_point(field_get:go.GameCowcowPlaying.BetScore)
  return betscore_;
}
inline void GameCowcowPlaying::set_betscore(::google::protobuf::int64 value) {
  
  betscore_ = value;
  // @@protoc_insertion_point(field_set:go.GameCowcowPlaying.BetScore)
}

// -------------------------------------------------------------------

// GameCowcowBetResult

// int32 State = 1;
inline void GameCowcowBetResult::clear_state() {
  state_ = 0;
}
inline ::google::protobuf::int32 GameCowcowBetResult::state() const {
  // @@protoc_insertion_point(field_get:go.GameCowcowBetResult.State)
  return state_;
}
inline void GameCowcowBetResult::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:go.GameCowcowBetResult.State)
}

// string Hints = 2;
inline void GameCowcowBetResult::clear_hints() {
  hints_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& GameCowcowBetResult::hints() const {
  // @@protoc_insertion_point(field_get:go.GameCowcowBetResult.Hints)
  return hints_.GetNoArena();
}
inline void GameCowcowBetResult::set_hints(const ::std::string& value) {
  
  hints_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:go.GameCowcowBetResult.Hints)
}
#if LANG_CXX11
inline void GameCowcowBetResult::set_hints(::std::string&& value) {
  
  hints_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:go.GameCowcowBetResult.Hints)
}
#endif
inline void GameCowcowBetResult::set_hints(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  hints_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:go.GameCowcowBetResult.Hints)
}
inline void GameCowcowBetResult::set_hints(const char* value, size_t size) {
  
  hints_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:go.GameCowcowBetResult.Hints)
}
inline ::std::string* GameCowcowBetResult::mutable_hints() {
  
  // @@protoc_insertion_point(field_mutable:go.GameCowcowBetResult.Hints)
  return hints_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* GameCowcowBetResult::release_hints() {
  // @@protoc_insertion_point(field_release:go.GameCowcowBetResult.Hints)
  
  return hints_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void GameCowcowBetResult::set_allocated_hints(::std::string* hints) {
  if (hints != nullptr) {
    
  } else {
    
  }
  hints_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hints);
  // @@protoc_insertion_point(field_set_allocated:go.GameCowcowBetResult.Hints)
}

// -------------------------------------------------------------------

// GameCowcowOver

// repeated int32 AwardArea = 1;
inline int GameCowcowOver::awardarea_size() const {
  return awardarea_.size();
}
inline void GameCowcowOver::clear_awardarea() {
  awardarea_.Clear();
}
inline ::google::protobuf::int32 GameCowcowOver::awardarea(int index) const {
  // @@protoc_insertion_point(field_get:go.GameCowcowOver.AwardArea)
  return awardarea_.Get(index);
}
inline void GameCowcowOver::set_awardarea(int index, ::google::protobuf::int32 value) {
  awardarea_.Set(index, value);
  // @@protoc_insertion_point(field_set:go.GameCowcowOver.AwardArea)
}
inline void GameCowcowOver::add_awardarea(::google::protobuf::int32 value) {
  awardarea_.Add(value);
  // @@protoc_insertion_point(field_add:go.GameCowcowOver.AwardArea)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
GameCowcowOver::awardarea() const {
  // @@protoc_insertion_point(field_list:go.GameCowcowOver.AwardArea)
  return awardarea_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
GameCowcowOver::mutable_awardarea() {
  // @@protoc_insertion_point(field_mutable_list:go.GameCowcowOver.AwardArea)
  return &awardarea_;
}

// repeated int32 PlayerCard = 2;
inline int GameCowcowOver::playercard_size() const {
  return playercard_.size();
}
inline void GameCowcowOver::clear_playercard() {
  playercard_.Clear();
}
inline ::google::protobuf::int32 GameCowcowOver::playercard(int index) const {
  // @@protoc_insertion_point(field_get:go.GameCowcowOver.PlayerCard)
  return playercard_.Get(index);
}
inline void GameCowcowOver::set_playercard(int index, ::google::protobuf::int32 value) {
  playercard_.Set(index, value);
  // @@protoc_insertion_point(field_set:go.GameCowcowOver.PlayerCard)
}
inline void GameCowcowOver::add_playercard(::google::protobuf::int32 value) {
  playercard_.Add(value);
  // @@protoc_insertion_point(field_add:go.GameCowcowOver.PlayerCard)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
GameCowcowOver::playercard() const {
  // @@protoc_insertion_point(field_list:go.GameCowcowOver.PlayerCard)
  return playercard_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
GameCowcowOver::mutable_playercard() {
  // @@protoc_insertion_point(field_mutable_list:go.GameCowcowOver.PlayerCard)
  return &playercard_;
}

// repeated int32 BankerCard = 3;
inline int GameCowcowOver::bankercard_size() const {
  return bankercard_.size();
}
inline void GameCowcowOver::clear_bankercard() {
  bankercard_.Clear();
}
inline ::google::protobuf::int32 GameCowcowOver::bankercard(int index) const {
  // @@protoc_insertion_point(field_get:go.GameCowcowOver.BankerCard)
  return bankercard_.Get(index);
}
inline void GameCowcowOver::set_bankercard(int index, ::google::protobuf::int32 value) {
  bankercard_.Set(index, value);
  // @@protoc_insertion_point(field_set:go.GameCowcowOver.BankerCard)
}
inline void GameCowcowOver::add_bankercard(::google::protobuf::int32 value) {
  bankercard_.Add(value);
  // @@protoc_insertion_point(field_add:go.GameCowcowOver.BankerCard)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
GameCowcowOver::bankercard() const {
  // @@protoc_insertion_point(field_list:go.GameCowcowOver.BankerCard)
  return bankercard_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
GameCowcowOver::mutable_bankercard() {
  // @@protoc_insertion_point(field_mutable_list:go.GameCowcowOver.BankerCard)
  return &bankercard_;
}

// int64 Acquire = 4;
inline void GameCowcowOver::clear_acquire() {
  acquire_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 GameCowcowOver::acquire() const {
  // @@protoc_insertion_point(field_get:go.GameCowcowOver.Acquire)
  return acquire_;
}
inline void GameCowcowOver::set_acquire(::google::protobuf::int64 value) {
  
  acquire_ = value;
  // @@protoc_insertion_point(field_set:go.GameCowcowOver.Acquire)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace go

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_cowcow_2eproto
