// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cowcow.proto

#include "cowcow.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace go {
class GameCowcowEnterDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GameCowcowEnter> _instance;
} _GameCowcowEnter_default_instance_;
class GameCowcowPlayingDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GameCowcowPlaying> _instance;
} _GameCowcowPlaying_default_instance_;
class GameCowcowBetResultDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GameCowcowBetResult> _instance;
} _GameCowcowBetResult_default_instance_;
class GameCowcowOverDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GameCowcowOver> _instance;
} _GameCowcowOver_default_instance_;
}  // namespace go
static void InitDefaultsGameCowcowEnter_cowcow_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::go::_GameCowcowEnter_default_instance_;
    new (ptr) ::go::GameCowcowEnter();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::go::GameCowcowEnter::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GameCowcowEnter_cowcow_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGameCowcowEnter_cowcow_2eproto}, {}};

static void InitDefaultsGameCowcowPlaying_cowcow_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::go::_GameCowcowPlaying_default_instance_;
    new (ptr) ::go::GameCowcowPlaying();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::go::GameCowcowPlaying::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GameCowcowPlaying_cowcow_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGameCowcowPlaying_cowcow_2eproto}, {}};

static void InitDefaultsGameCowcowBetResult_cowcow_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::go::_GameCowcowBetResult_default_instance_;
    new (ptr) ::go::GameCowcowBetResult();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::go::GameCowcowBetResult::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GameCowcowBetResult_cowcow_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGameCowcowBetResult_cowcow_2eproto}, {}};

static void InitDefaultsGameCowcowOver_cowcow_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::go::_GameCowcowOver_default_instance_;
    new (ptr) ::go::GameCowcowOver();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::go::GameCowcowOver::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GameCowcowOver_cowcow_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGameCowcowOver_cowcow_2eproto}, {}};

void InitDefaults_cowcow_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_GameCowcowEnter_cowcow_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GameCowcowPlaying_cowcow_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GameCowcowBetResult_cowcow_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GameCowcowOver_cowcow_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_cowcow_2eproto[4];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_cowcow_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_cowcow_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_cowcow_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowEnter, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowEnter, awardareas_),
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowEnter, players_),
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowEnter, countdown_),
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowEnter, chips_),
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowEnter, odds_),
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowEnter, bankerscore_),
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowEnter, playerscore_),
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowEnter, acquire_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowPlaying, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowPlaying, betarea_),
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowPlaying, betscore_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowBetResult, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowBetResult, state_),
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowBetResult, hints_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowOver, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowOver, awardarea_),
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowOver, playercard_),
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowOver, bankercard_),
  PROTOBUF_FIELD_OFFSET(::go::GameCowcowOver, acquire_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::go::GameCowcowEnter)},
  { 13, -1, sizeof(::go::GameCowcowPlaying)},
  { 20, -1, sizeof(::go::GameCowcowBetResult)},
  { 27, -1, sizeof(::go::GameCowcowOver)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::go::_GameCowcowEnter_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::go::_GameCowcowPlaying_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::go::_GameCowcowBetResult_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::go::_GameCowcowOver_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_cowcow_2eproto = {
  {}, AddDescriptors_cowcow_2eproto, "cowcow.proto", schemas,
  file_default_instances, TableStruct_cowcow_2eproto::offsets,
  file_level_metadata_cowcow_2eproto, 4, file_level_enum_descriptors_cowcow_2eproto, file_level_service_descriptors_cowcow_2eproto,
};

const char descriptor_table_protodef_cowcow_2eproto[] =
  "\n\014cowcow.proto\022\002go\"\241\001\n\017GameCowcowEnter\022\022"
  "\n\nAwardAreas\030\001 \003(\005\022\017\n\007players\030\002 \003(\t\022\021\n\tC"
  "ountdown\030\003 \001(\005\022\r\n\005Chips\030\004 \003(\005\022\014\n\004Odds\030\005 "
  "\003(\005\022\023\n\013BankerScore\030\006 \001(\003\022\023\n\013PlayerScore\030"
  "\007 \001(\003\022\017\n\007Acquire\030\010 \001(\003\"6\n\021GameCowcowPlay"
  "ing\022\017\n\007BetArea\030\001 \001(\005\022\020\n\010BetScore\030\002 \001(\003\"3"
  "\n\023GameCowcowBetResult\022\r\n\005State\030\001 \001(\005\022\r\n\005"
  "Hints\030\002 \001(\t\"\\\n\016GameCowcowOver\022\021\n\tAwardAr"
  "ea\030\001 \003(\005\022\022\n\nPlayerCard\030\002 \003(\005\022\022\n\nBankerCa"
  "rd\030\003 \003(\005\022\017\n\007Acquire\030\004 \001(\003b\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_cowcow_2eproto = {
  false, InitDefaults_cowcow_2eproto, 
  descriptor_table_protodef_cowcow_2eproto,
  "cowcow.proto", &assign_descriptors_table_cowcow_2eproto, 393,
};

void AddDescriptors_cowcow_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_cowcow_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_cowcow_2eproto = []() { AddDescriptors_cowcow_2eproto(); return true; }();
namespace go {

// ===================================================================

void GameCowcowEnter::InitAsDefaultInstance() {
}
class GameCowcowEnter::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GameCowcowEnter::kAwardAreasFieldNumber;
const int GameCowcowEnter::kPlayersFieldNumber;
const int GameCowcowEnter::kCountdownFieldNumber;
const int GameCowcowEnter::kChipsFieldNumber;
const int GameCowcowEnter::kOddsFieldNumber;
const int GameCowcowEnter::kBankerScoreFieldNumber;
const int GameCowcowEnter::kPlayerScoreFieldNumber;
const int GameCowcowEnter::kAcquireFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GameCowcowEnter::GameCowcowEnter()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:go.GameCowcowEnter)
}
GameCowcowEnter::GameCowcowEnter(const GameCowcowEnter& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      awardareas_(from.awardareas_),
      players_(from.players_),
      chips_(from.chips_),
      odds_(from.odds_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&bankerscore_, &from.bankerscore_,
    static_cast<size_t>(reinterpret_cast<char*>(&countdown_) -
    reinterpret_cast<char*>(&bankerscore_)) + sizeof(countdown_));
  // @@protoc_insertion_point(copy_constructor:go.GameCowcowEnter)
}

void GameCowcowEnter::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_GameCowcowEnter_cowcow_2eproto.base);
  ::memset(&bankerscore_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&countdown_) -
      reinterpret_cast<char*>(&bankerscore_)) + sizeof(countdown_));
}

GameCowcowEnter::~GameCowcowEnter() {
  // @@protoc_insertion_point(destructor:go.GameCowcowEnter)
  SharedDtor();
}

void GameCowcowEnter::SharedDtor() {
}

void GameCowcowEnter::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GameCowcowEnter& GameCowcowEnter::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_GameCowcowEnter_cowcow_2eproto.base);
  return *internal_default_instance();
}


void GameCowcowEnter::Clear() {
// @@protoc_insertion_point(message_clear_start:go.GameCowcowEnter)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  awardareas_.Clear();
  players_.Clear();
  chips_.Clear();
  odds_.Clear();
  ::memset(&bankerscore_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&countdown_) -
      reinterpret_cast<char*>(&bankerscore_)) + sizeof(countdown_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* GameCowcowEnter::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<GameCowcowEnter*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // repeated int32 AwardAreas = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) == 10) {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::google::protobuf::internal::PackedInt32Parser;
          object = msg->mutable_awardareas();
          if (size > end - ptr) goto len_delim_till_end;
          auto newend = ptr + size;
          if (size) ptr = parser_till_end(ptr, newend, object, ctx);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr == newend);
          break;
        } else if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        do {
          msg->add_awardareas(::google::protobuf::internal::ReadVarint(&ptr));
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 8 && (ptr += 1));
        break;
      }
      // repeated string players = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          ctx->extra_parse_data().SetFieldName("go.GameCowcowEnter.players");
          object = msg->add_players();
          if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
            parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
            goto string_till_end;
          }
          GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
          ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
          ptr += size;
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 18 && (ptr += 1));
        break;
      }
      // int32 Countdown = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        msg->set_countdown(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // repeated int32 Chips = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) == 34) {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::google::protobuf::internal::PackedInt32Parser;
          object = msg->mutable_chips();
          if (size > end - ptr) goto len_delim_till_end;
          auto newend = ptr + size;
          if (size) ptr = parser_till_end(ptr, newend, object, ctx);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr == newend);
          break;
        } else if (static_cast<::google::protobuf::uint8>(tag) != 32) goto handle_unusual;
        do {
          msg->add_chips(::google::protobuf::internal::ReadVarint(&ptr));
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 32 && (ptr += 1));
        break;
      }
      // repeated int32 Odds = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) == 42) {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::google::protobuf::internal::PackedInt32Parser;
          object = msg->mutable_odds();
          if (size > end - ptr) goto len_delim_till_end;
          auto newend = ptr + size;
          if (size) ptr = parser_till_end(ptr, newend, object, ctx);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr == newend);
          break;
        } else if (static_cast<::google::protobuf::uint8>(tag) != 40) goto handle_unusual;
        do {
          msg->add_odds(::google::protobuf::internal::ReadVarint(&ptr));
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 40 && (ptr += 1));
        break;
      }
      // int64 BankerScore = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 48) goto handle_unusual;
        msg->set_bankerscore(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // int64 PlayerScore = 7;
      case 7: {
        if (static_cast<::google::protobuf::uint8>(tag) != 56) goto handle_unusual;
        msg->set_playerscore(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // int64 Acquire = 8;
      case 8: {
        if (static_cast<::google::protobuf::uint8>(tag) != 64) goto handle_unusual;
        msg->set_acquire(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool GameCowcowEnter::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:go.GameCowcowEnter)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 AwardAreas = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_awardareas())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 10u, input, this->mutable_awardareas())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string players = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_players()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->players(this->players_size() - 1).data(),
            static_cast<int>(this->players(this->players_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "go.GameCowcowEnter.players"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 Countdown = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &countdown_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 Chips = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_chips())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) == (32 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 34u, input, this->mutable_chips())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 Odds = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (42 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_odds())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) == (40 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 42u, input, this->mutable_odds())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 BankerScore = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (48 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &bankerscore_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 PlayerScore = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (56 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &playerscore_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 Acquire = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (64 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &acquire_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:go.GameCowcowEnter)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:go.GameCowcowEnter)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void GameCowcowEnter::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:go.GameCowcowEnter)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 AwardAreas = 1;
  if (this->awardareas_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_awardareas_cached_byte_size_.load(
        std::memory_order_relaxed));
  }
  for (int i = 0, n = this->awardareas_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->awardareas(i), output);
  }

  // repeated string players = 2;
  for (int i = 0, n = this->players_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->players(i).data(), static_cast<int>(this->players(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "go.GameCowcowEnter.players");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->players(i), output);
  }

  // int32 Countdown = 3;
  if (this->countdown() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->countdown(), output);
  }

  // repeated int32 Chips = 4;
  if (this->chips_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(4, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_chips_cached_byte_size_.load(
        std::memory_order_relaxed));
  }
  for (int i = 0, n = this->chips_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->chips(i), output);
  }

  // repeated int32 Odds = 5;
  if (this->odds_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(5, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_odds_cached_byte_size_.load(
        std::memory_order_relaxed));
  }
  for (int i = 0, n = this->odds_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->odds(i), output);
  }

  // int64 BankerScore = 6;
  if (this->bankerscore() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(6, this->bankerscore(), output);
  }

  // int64 PlayerScore = 7;
  if (this->playerscore() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(7, this->playerscore(), output);
  }

  // int64 Acquire = 8;
  if (this->acquire() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(8, this->acquire(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:go.GameCowcowEnter)
}

::google::protobuf::uint8* GameCowcowEnter::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:go.GameCowcowEnter)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 AwardAreas = 1;
  if (this->awardareas_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        _awardareas_cached_byte_size_.load(std::memory_order_relaxed),
         target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->awardareas_, target);
  }

  // repeated string players = 2;
  for (int i = 0, n = this->players_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->players(i).data(), static_cast<int>(this->players(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "go.GameCowcowEnter.players");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->players(i), target);
  }

  // int32 Countdown = 3;
  if (this->countdown() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->countdown(), target);
  }

  // repeated int32 Chips = 4;
  if (this->chips_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      4,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        _chips_cached_byte_size_.load(std::memory_order_relaxed),
         target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->chips_, target);
  }

  // repeated int32 Odds = 5;
  if (this->odds_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      5,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        _odds_cached_byte_size_.load(std::memory_order_relaxed),
         target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->odds_, target);
  }

  // int64 BankerScore = 6;
  if (this->bankerscore() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(6, this->bankerscore(), target);
  }

  // int64 PlayerScore = 7;
  if (this->playerscore() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(7, this->playerscore(), target);
  }

  // int64 Acquire = 8;
  if (this->acquire() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(8, this->acquire(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:go.GameCowcowEnter)
  return target;
}

size_t GameCowcowEnter::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:go.GameCowcowEnter)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 AwardAreas = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->awardareas_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast<::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    _awardareas_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated string players = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->players_size());
  for (int i = 0, n = this->players_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->players(i));
  }

  // repeated int32 Chips = 4;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->chips_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast<::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    _chips_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated int32 Odds = 5;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->odds_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast<::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    _odds_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // int64 BankerScore = 6;
  if (this->bankerscore() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->bankerscore());
  }

  // int64 PlayerScore = 7;
  if (this->playerscore() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->playerscore());
  }

  // int64 Acquire = 8;
  if (this->acquire() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->acquire());
  }

  // int32 Countdown = 3;
  if (this->countdown() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->countdown());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GameCowcowEnter::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:go.GameCowcowEnter)
  GOOGLE_DCHECK_NE(&from, this);
  const GameCowcowEnter* source =
      ::google::protobuf::DynamicCastToGenerated<GameCowcowEnter>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:go.GameCowcowEnter)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:go.GameCowcowEnter)
    MergeFrom(*source);
  }
}

void GameCowcowEnter::MergeFrom(const GameCowcowEnter& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:go.GameCowcowEnter)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  awardareas_.MergeFrom(from.awardareas_);
  players_.MergeFrom(from.players_);
  chips_.MergeFrom(from.chips_);
  odds_.MergeFrom(from.odds_);
  if (from.bankerscore() != 0) {
    set_bankerscore(from.bankerscore());
  }
  if (from.playerscore() != 0) {
    set_playerscore(from.playerscore());
  }
  if (from.acquire() != 0) {
    set_acquire(from.acquire());
  }
  if (from.countdown() != 0) {
    set_countdown(from.countdown());
  }
}

void GameCowcowEnter::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:go.GameCowcowEnter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GameCowcowEnter::CopyFrom(const GameCowcowEnter& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:go.GameCowcowEnter)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameCowcowEnter::IsInitialized() const {
  return true;
}

void GameCowcowEnter::Swap(GameCowcowEnter* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GameCowcowEnter::InternalSwap(GameCowcowEnter* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  awardareas_.InternalSwap(&other->awardareas_);
  players_.InternalSwap(CastToBase(&other->players_));
  chips_.InternalSwap(&other->chips_);
  odds_.InternalSwap(&other->odds_);
  swap(bankerscore_, other->bankerscore_);
  swap(playerscore_, other->playerscore_);
  swap(acquire_, other->acquire_);
  swap(countdown_, other->countdown_);
}

::google::protobuf::Metadata GameCowcowEnter::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_cowcow_2eproto);
  return ::file_level_metadata_cowcow_2eproto[kIndexInFileMessages];
}


// ===================================================================

void GameCowcowPlaying::InitAsDefaultInstance() {
}
class GameCowcowPlaying::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GameCowcowPlaying::kBetAreaFieldNumber;
const int GameCowcowPlaying::kBetScoreFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GameCowcowPlaying::GameCowcowPlaying()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:go.GameCowcowPlaying)
}
GameCowcowPlaying::GameCowcowPlaying(const GameCowcowPlaying& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&betscore_, &from.betscore_,
    static_cast<size_t>(reinterpret_cast<char*>(&betarea_) -
    reinterpret_cast<char*>(&betscore_)) + sizeof(betarea_));
  // @@protoc_insertion_point(copy_constructor:go.GameCowcowPlaying)
}

void GameCowcowPlaying::SharedCtor() {
  ::memset(&betscore_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&betarea_) -
      reinterpret_cast<char*>(&betscore_)) + sizeof(betarea_));
}

GameCowcowPlaying::~GameCowcowPlaying() {
  // @@protoc_insertion_point(destructor:go.GameCowcowPlaying)
  SharedDtor();
}

void GameCowcowPlaying::SharedDtor() {
}

void GameCowcowPlaying::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GameCowcowPlaying& GameCowcowPlaying::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_GameCowcowPlaying_cowcow_2eproto.base);
  return *internal_default_instance();
}


void GameCowcowPlaying::Clear() {
// @@protoc_insertion_point(message_clear_start:go.GameCowcowPlaying)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&betscore_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&betarea_) -
      reinterpret_cast<char*>(&betscore_)) + sizeof(betarea_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* GameCowcowPlaying::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<GameCowcowPlaying*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 BetArea = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_betarea(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // int64 BetScore = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_betscore(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool GameCowcowPlaying::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:go.GameCowcowPlaying)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 BetArea = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &betarea_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 BetScore = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &betscore_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:go.GameCowcowPlaying)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:go.GameCowcowPlaying)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void GameCowcowPlaying::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:go.GameCowcowPlaying)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 BetArea = 1;
  if (this->betarea() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->betarea(), output);
  }

  // int64 BetScore = 2;
  if (this->betscore() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->betscore(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:go.GameCowcowPlaying)
}

::google::protobuf::uint8* GameCowcowPlaying::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:go.GameCowcowPlaying)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 BetArea = 1;
  if (this->betarea() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->betarea(), target);
  }

  // int64 BetScore = 2;
  if (this->betscore() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->betscore(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:go.GameCowcowPlaying)
  return target;
}

size_t GameCowcowPlaying::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:go.GameCowcowPlaying)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 BetScore = 2;
  if (this->betscore() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->betscore());
  }

  // int32 BetArea = 1;
  if (this->betarea() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->betarea());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GameCowcowPlaying::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:go.GameCowcowPlaying)
  GOOGLE_DCHECK_NE(&from, this);
  const GameCowcowPlaying* source =
      ::google::protobuf::DynamicCastToGenerated<GameCowcowPlaying>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:go.GameCowcowPlaying)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:go.GameCowcowPlaying)
    MergeFrom(*source);
  }
}

void GameCowcowPlaying::MergeFrom(const GameCowcowPlaying& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:go.GameCowcowPlaying)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.betscore() != 0) {
    set_betscore(from.betscore());
  }
  if (from.betarea() != 0) {
    set_betarea(from.betarea());
  }
}

void GameCowcowPlaying::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:go.GameCowcowPlaying)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GameCowcowPlaying::CopyFrom(const GameCowcowPlaying& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:go.GameCowcowPlaying)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameCowcowPlaying::IsInitialized() const {
  return true;
}

void GameCowcowPlaying::Swap(GameCowcowPlaying* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GameCowcowPlaying::InternalSwap(GameCowcowPlaying* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(betscore_, other->betscore_);
  swap(betarea_, other->betarea_);
}

::google::protobuf::Metadata GameCowcowPlaying::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_cowcow_2eproto);
  return ::file_level_metadata_cowcow_2eproto[kIndexInFileMessages];
}


// ===================================================================

void GameCowcowBetResult::InitAsDefaultInstance() {
}
class GameCowcowBetResult::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GameCowcowBetResult::kStateFieldNumber;
const int GameCowcowBetResult::kHintsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GameCowcowBetResult::GameCowcowBetResult()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:go.GameCowcowBetResult)
}
GameCowcowBetResult::GameCowcowBetResult(const GameCowcowBetResult& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  hints_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.hints().size() > 0) {
    hints_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hints_);
  }
  state_ = from.state_;
  // @@protoc_insertion_point(copy_constructor:go.GameCowcowBetResult)
}

void GameCowcowBetResult::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_GameCowcowBetResult_cowcow_2eproto.base);
  hints_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  state_ = 0;
}

GameCowcowBetResult::~GameCowcowBetResult() {
  // @@protoc_insertion_point(destructor:go.GameCowcowBetResult)
  SharedDtor();
}

void GameCowcowBetResult::SharedDtor() {
  hints_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GameCowcowBetResult::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GameCowcowBetResult& GameCowcowBetResult::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_GameCowcowBetResult_cowcow_2eproto.base);
  return *internal_default_instance();
}


void GameCowcowBetResult::Clear() {
// @@protoc_insertion_point(message_clear_start:go.GameCowcowBetResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  hints_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  state_ = 0;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* GameCowcowBetResult::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<GameCowcowBetResult*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 State = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_state(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // string Hints = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("go.GameCowcowBetResult.Hints");
        object = msg->mutable_hints();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool GameCowcowBetResult::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:go.GameCowcowBetResult)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 State = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &state_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string Hints = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hints()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->hints().data(), static_cast<int>(this->hints().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "go.GameCowcowBetResult.Hints"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:go.GameCowcowBetResult)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:go.GameCowcowBetResult)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void GameCowcowBetResult::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:go.GameCowcowBetResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 State = 1;
  if (this->state() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->state(), output);
  }

  // string Hints = 2;
  if (this->hints().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hints().data(), static_cast<int>(this->hints().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "go.GameCowcowBetResult.Hints");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->hints(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:go.GameCowcowBetResult)
}

::google::protobuf::uint8* GameCowcowBetResult::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:go.GameCowcowBetResult)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 State = 1;
  if (this->state() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->state(), target);
  }

  // string Hints = 2;
  if (this->hints().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hints().data(), static_cast<int>(this->hints().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "go.GameCowcowBetResult.Hints");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->hints(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:go.GameCowcowBetResult)
  return target;
}

size_t GameCowcowBetResult::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:go.GameCowcowBetResult)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string Hints = 2;
  if (this->hints().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hints());
  }

  // int32 State = 1;
  if (this->state() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->state());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GameCowcowBetResult::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:go.GameCowcowBetResult)
  GOOGLE_DCHECK_NE(&from, this);
  const GameCowcowBetResult* source =
      ::google::protobuf::DynamicCastToGenerated<GameCowcowBetResult>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:go.GameCowcowBetResult)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:go.GameCowcowBetResult)
    MergeFrom(*source);
  }
}

void GameCowcowBetResult::MergeFrom(const GameCowcowBetResult& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:go.GameCowcowBetResult)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.hints().size() > 0) {

    hints_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hints_);
  }
  if (from.state() != 0) {
    set_state(from.state());
  }
}

void GameCowcowBetResult::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:go.GameCowcowBetResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GameCowcowBetResult::CopyFrom(const GameCowcowBetResult& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:go.GameCowcowBetResult)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameCowcowBetResult::IsInitialized() const {
  return true;
}

void GameCowcowBetResult::Swap(GameCowcowBetResult* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GameCowcowBetResult::InternalSwap(GameCowcowBetResult* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  hints_.Swap(&other->hints_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(state_, other->state_);
}

::google::protobuf::Metadata GameCowcowBetResult::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_cowcow_2eproto);
  return ::file_level_metadata_cowcow_2eproto[kIndexInFileMessages];
}


// ===================================================================

void GameCowcowOver::InitAsDefaultInstance() {
}
class GameCowcowOver::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GameCowcowOver::kAwardAreaFieldNumber;
const int GameCowcowOver::kPlayerCardFieldNumber;
const int GameCowcowOver::kBankerCardFieldNumber;
const int GameCowcowOver::kAcquireFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GameCowcowOver::GameCowcowOver()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:go.GameCowcowOver)
}
GameCowcowOver::GameCowcowOver(const GameCowcowOver& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      awardarea_(from.awardarea_),
      playercard_(from.playercard_),
      bankercard_(from.bankercard_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  acquire_ = from.acquire_;
  // @@protoc_insertion_point(copy_constructor:go.GameCowcowOver)
}

void GameCowcowOver::SharedCtor() {
  acquire_ = PROTOBUF_LONGLONG(0);
}

GameCowcowOver::~GameCowcowOver() {
  // @@protoc_insertion_point(destructor:go.GameCowcowOver)
  SharedDtor();
}

void GameCowcowOver::SharedDtor() {
}

void GameCowcowOver::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const GameCowcowOver& GameCowcowOver::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_GameCowcowOver_cowcow_2eproto.base);
  return *internal_default_instance();
}


void GameCowcowOver::Clear() {
// @@protoc_insertion_point(message_clear_start:go.GameCowcowOver)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  awardarea_.Clear();
  playercard_.Clear();
  bankercard_.Clear();
  acquire_ = PROTOBUF_LONGLONG(0);
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* GameCowcowOver::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<GameCowcowOver*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // repeated int32 AwardArea = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) == 10) {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::google::protobuf::internal::PackedInt32Parser;
          object = msg->mutable_awardarea();
          if (size > end - ptr) goto len_delim_till_end;
          auto newend = ptr + size;
          if (size) ptr = parser_till_end(ptr, newend, object, ctx);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr == newend);
          break;
        } else if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        do {
          msg->add_awardarea(::google::protobuf::internal::ReadVarint(&ptr));
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 8 && (ptr += 1));
        break;
      }
      // repeated int32 PlayerCard = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) == 18) {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::google::protobuf::internal::PackedInt32Parser;
          object = msg->mutable_playercard();
          if (size > end - ptr) goto len_delim_till_end;
          auto newend = ptr + size;
          if (size) ptr = parser_till_end(ptr, newend, object, ctx);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr == newend);
          break;
        } else if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        do {
          msg->add_playercard(::google::protobuf::internal::ReadVarint(&ptr));
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 16 && (ptr += 1));
        break;
      }
      // repeated int32 BankerCard = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) == 26) {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::google::protobuf::internal::PackedInt32Parser;
          object = msg->mutable_bankercard();
          if (size > end - ptr) goto len_delim_till_end;
          auto newend = ptr + size;
          if (size) ptr = parser_till_end(ptr, newend, object, ctx);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr == newend);
          break;
        } else if (static_cast<::google::protobuf::uint8>(tag) != 24) goto handle_unusual;
        do {
          msg->add_bankercard(::google::protobuf::internal::ReadVarint(&ptr));
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 24 && (ptr += 1));
        break;
      }
      // int64 Acquire = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 32) goto handle_unusual;
        msg->set_acquire(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool GameCowcowOver::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:go.GameCowcowOver)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated int32 AwardArea = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_awardarea())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 10u, input, this->mutable_awardarea())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 PlayerCard = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_playercard())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 18u, input, this->mutable_playercard())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated int32 BankerCard = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_bankercard())));
        } else if (static_cast< ::google::protobuf::uint8>(tag) == (24 & 0xFF)) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 26u, input, this->mutable_bankercard())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 Acquire = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (32 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &acquire_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:go.GameCowcowOver)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:go.GameCowcowOver)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void GameCowcowOver::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:go.GameCowcowOver)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 AwardArea = 1;
  if (this->awardarea_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(1, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_awardarea_cached_byte_size_.load(
        std::memory_order_relaxed));
  }
  for (int i = 0, n = this->awardarea_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->awardarea(i), output);
  }

  // repeated int32 PlayerCard = 2;
  if (this->playercard_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(2, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_playercard_cached_byte_size_.load(
        std::memory_order_relaxed));
  }
  for (int i = 0, n = this->playercard_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->playercard(i), output);
  }

  // repeated int32 BankerCard = 3;
  if (this->bankercard_size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteTag(3, ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(_bankercard_cached_byte_size_.load(
        std::memory_order_relaxed));
  }
  for (int i = 0, n = this->bankercard_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32NoTag(
      this->bankercard(i), output);
  }

  // int64 Acquire = 4;
  if (this->acquire() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->acquire(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:go.GameCowcowOver)
}

::google::protobuf::uint8* GameCowcowOver::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:go.GameCowcowOver)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated int32 AwardArea = 1;
  if (this->awardarea_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      1,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        _awardarea_cached_byte_size_.load(std::memory_order_relaxed),
         target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->awardarea_, target);
  }

  // repeated int32 PlayerCard = 2;
  if (this->playercard_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      2,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        _playercard_cached_byte_size_.load(std::memory_order_relaxed),
         target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->playercard_, target);
  }

  // repeated int32 BankerCard = 3;
  if (this->bankercard_size() > 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        _bankercard_cached_byte_size_.load(std::memory_order_relaxed),
         target);
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32NoTagToArray(this->bankercard_, target);
  }

  // int64 Acquire = 4;
  if (this->acquire() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->acquire(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:go.GameCowcowOver)
  return target;
}

size_t GameCowcowOver::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:go.GameCowcowOver)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated int32 AwardArea = 1;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->awardarea_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast<::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    _awardarea_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated int32 PlayerCard = 2;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->playercard_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast<::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    _playercard_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated int32 BankerCard = 3;
  {
    size_t data_size = ::google::protobuf::internal::WireFormatLite::
      Int32Size(this->bankercard_);
    if (data_size > 0) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast<::google::protobuf::int32>(data_size));
    }
    int cached_size = ::google::protobuf::internal::ToCachedSize(data_size);
    _bankercard_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // int64 Acquire = 4;
  if (this->acquire() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->acquire());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GameCowcowOver::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:go.GameCowcowOver)
  GOOGLE_DCHECK_NE(&from, this);
  const GameCowcowOver* source =
      ::google::protobuf::DynamicCastToGenerated<GameCowcowOver>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:go.GameCowcowOver)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:go.GameCowcowOver)
    MergeFrom(*source);
  }
}

void GameCowcowOver::MergeFrom(const GameCowcowOver& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:go.GameCowcowOver)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  awardarea_.MergeFrom(from.awardarea_);
  playercard_.MergeFrom(from.playercard_);
  bankercard_.MergeFrom(from.bankercard_);
  if (from.acquire() != 0) {
    set_acquire(from.acquire());
  }
}

void GameCowcowOver::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:go.GameCowcowOver)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GameCowcowOver::CopyFrom(const GameCowcowOver& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:go.GameCowcowOver)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GameCowcowOver::IsInitialized() const {
  return true;
}

void GameCowcowOver::Swap(GameCowcowOver* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GameCowcowOver::InternalSwap(GameCowcowOver* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  awardarea_.InternalSwap(&other->awardarea_);
  playercard_.InternalSwap(&other->playercard_);
  bankercard_.InternalSwap(&other->bankercard_);
  swap(acquire_, other->acquire_);
}

::google::protobuf::Metadata GameCowcowOver::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_cowcow_2eproto);
  return ::file_level_metadata_cowcow_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace go
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::go::GameCowcowEnter* Arena::CreateMaybeMessage< ::go::GameCowcowEnter >(Arena* arena) {
  return Arena::CreateInternal< ::go::GameCowcowEnter >(arena);
}
template<> PROTOBUF_NOINLINE ::go::GameCowcowPlaying* Arena::CreateMaybeMessage< ::go::GameCowcowPlaying >(Arena* arena) {
  return Arena::CreateInternal< ::go::GameCowcowPlaying >(arena);
}
template<> PROTOBUF_NOINLINE ::go::GameCowcowBetResult* Arena::CreateMaybeMessage< ::go::GameCowcowBetResult >(Arena* arena) {
  return Arena::CreateInternal< ::go::GameCowcowBetResult >(arena);
}
template<> PROTOBUF_NOINLINE ::go::GameCowcowOver* Arena::CreateMaybeMessage< ::go::GameCowcowOver >(Arena* arena) {
  return Arena::CreateInternal< ::go::GameCowcowOver >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
